[package]
name = "gourd"
version = "0.1.0"
edition = "2018"


[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "gourd"

[dependencies]
actix-web = "4.0.0-beta.4"
futures = "0.3"
env_logger = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "^1.0"
url = "1.7"
ingredient = {git = "https://github.com/nickysemenza/ingredient-parser", branch = "main"}
actix-web-opentelemetry = "0.11.0-beta.1"
opentelemetry-jaeger = "0.11.0"
opentelemetry = "0.12.0"
sqlx = { version = "0.5.1", default-features = false, features = [ "runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline","bigdecimal"] }
serde-aux = "1.1.0"
config = { version = "0.10.1", default-features = false, features = ["yaml"] }
bigdecimal = { version = "0.2.0", features = ["serde"] }


gourd_common = {path = "../common"}
openapi = {path = "../openapi"}

[dev-dependencies]
actix-rt = "1"
