[package]
name = "json-example"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3"
actix-service = "1.0.0"
futures = "0.3"
env_logger = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "^1.0"
url = "1.5"
ingredient = {git = "https://github.com/nickysemenza/ingredient-parser", branch = "main"}
actix-web-opentelemetry = "0.10.0"
opentelemetry-jaeger = "0.11.0"
opentelemetry = "0.12.0"

gourd_common = {path = "../common"}
openapi = {path = "../openapi"}

[dev-dependencies]
actix-rt = "1"
