language: go
go:
  - 1.9
node_js: '7'
services:
  - mysql
env:
  global:
  - DEP_VERSION="0.3.2"
  - DB_USERNAME=root
  - DB_PASSWORD=
  - DB_DATABASE_TEST=food_test
before_install:
- nvm install 6.9
- nvm use 6.9
install:
- npm install -g yarn
- go get -u github.com/golang/dep/...
- cd backend/
- dep ensure
- cd ..
before_script:
- mysql -e 'CREATE DATABASE food_test;'
- cd frontend/
- yarn install
# - cp src/config.example.js src/config.js
- cd ..
script:
- cd backend/
- ./test_cov.sh
- cd ..
- cd frontend/
- npm test -- --coverage
- cd ..
after_success:
- cd backend/
- bash <(curl -s https://codecov.io/bash)
- cd ..
- cd frontend/
- bash <(curl -s https://codecov.io/bash)
- cd ..