language: go
go:
  - 1.6
node_js: '7'
env:
  - DEP_VERSION="0.3.2"
before_install:
- nvm install 6.9
- nvm use 6.9
# Download the binary to bin folder in $GOPATH
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
# Make the binary executable
- chmod +x $GOPATH/bin/dep
install:
- npm install -g yarn
before_script:
- cd backend/
- dep ensure
- cd ..
- cd frontend/
- yarn install
# - cp src/config.example.js src/config.js
- cd ..
script:
- cd backend/
- go test -v ./...
- cd ..
- cd frontend/
- npm test -- --coverage
- cd ..
after_success:
- cd backend/
- bash <(curl -s https://codecov.io/bash)
- cd ..
- cd frontend/
- bash <(curl -s https://codecov.io/bash)
- cd ..