[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.0.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.53"
