openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Recipestore
  license:
    name: MIT
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/nickysemenza/sss/1.0.0
  - url: http://recipestore.swagger.io/v1
paths:
  /ingredients:
    get:
      summary: List all ingredients
      operationId: list_ingredients
      parameters:
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: A page of ingredient results
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedIngredients"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /recipes:
    get:
      summary: List all recipes
      operationId: list_recipes
      tags:
        - recipes
      parameters:
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: A paged array of recipes
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedRecipes"
          # content:
          #   application/json:
          #     schema:
          #       allOf:
          #         - $ref: "#/components/schemas/List"
          #         - type: object
          #           properties:
          #             items:
          #               # type: object
          #               # items:
          #               $ref: "#/components/schemas/Recipes"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a recipe
      operationId: create_recipes
      tags:
        - recipes
      responses:
        "201":
          description: Newly created recipe
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recipe"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /recipes/{recipe_id}:
    get:
      summary: Info for a specific recipe
      operationId: get_recipe_by_id
      tags:
        - recipes
      parameters:
        - name: recipe_id
          in: path
          required: true
          description: The id of the recipe to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recipe"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Recipe:
      description: A recipe
      type: object
      required:
        - id
        - name
        - quantity
        - unit
      properties:
        id:
          description: UUID
          type: string
        name:
          description: recipe name
          type: string
        total_minutes:
          description: todo
          type: integer
        source:
          description: book or website? deprecated?
          type: string
        servings:
          description: num servings
          type: integer
        quantity:
          description: serving quantity
          type: integer
        unit:
          description: serving unit
          type: string
        # tag:
        # type: string
    Ingredient:
      description: "An Ingredient"
      type: object
      required:
        - id
        - name
      properties:
        id:
          description: UUID
          type: string
        name:
          description: Ingredient name
          type: string
        recipes:
          description: Recipes referencing this ingredient
          type: array
          items:
            $ref: "#/components/schemas/Recipe"
        children:
          description: Ingredients that are equivalent
          type: array
          items:
            $ref: "#/components/schemas/Ingredient"
    # Recipes:
    #   type: array
    #   items:
    #     $ref: "#/components/schemas/Recipe"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    List:
      type: object
      required:
        - page_number
        - limit
        - total_count
        - offset
      properties:
        page_number:
          description: What number page this is
          type: integer
        limit:
          description: How many items were requested for this page
          type: integer
        offset:
          description: todo
          type: integer
        total_count:
          description: Total number of items across all pages
          type: integer

    PaginatedRecipes:
      type: object
      properties:
        recipes:
          type: array
          items:
            $ref: "#/components/schemas/Recipe"
        # data2:
        #   $ref: "#/components/schemas/Recipes"
        meta:
          $ref: "#/components/schemas/List"
    PaginatedIngredients:
      type: object
      properties:
        ingredients:
          type: array
          items:
            $ref: "#/components/schemas/Ingredient"
        meta:
          $ref: "#/components/schemas/List"
  parameters:
    offsetParam:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before starting to collect the result set.
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: The numbers of items to return.
