openapi: "3.0.0"
info:
  version: 1.0.0
  title: Gourd Recipe Database
  license:
    name: MIT
servers:
  - description: test
    url: http://localhost:4242/api
  - description: prod
    url: https://food.nickysemenza.com/api
paths:
  /auth:
    post:
      summary: Google Login callback
      description: Second step of https://developers.google.com/identity/sign-in/web/backend-auth#send-the-id-token-to-your-server
      security: []
      operationId: auth_login
      tags:
        - authentication
      parameters:
        - in: query
          name: code
          required: true
          schema:
            type: string
          description: Google code
      responses:
        "200":
          description: Auth response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResp"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /photos:
    get:
      summary: List all photos
      operationId: list_photos
      tags:
        - photos
      parameters:
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: A page of photos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedPhotos"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /albums:
    get:
      summary: List all albums
      operationId: list_all_albums
      tags:
        - albums
      responses:
        "200":
          description: All available albums from google
          content:
            application/json:
              schema:
                type: object
                properties:
                  albums:
                    type: array
                    items:
                      $ref: "#/components/schemas/GooglePhotosAlbum"   
                    description: The list of albums
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"                
  /search:
    get:
      summary: Search recipes and ingredients
      operationId: search
      tags:
        - ingredients
        - recipes
      parameters:
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"        
        - $ref: "#/components/parameters/nameParam"        
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResult"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"                          
  /meals:
    get:
      summary: List all meals
      operationId: list_meals
      tags:
        - meals
      parameters:
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: A page of meals
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedMeals"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /ingredients:
    get:
      summary: List all ingredients
      operationId: list_ingredients
      tags:
        - ingredients
      parameters:
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: A page of ingredient results
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedIngredients"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a ingredient
      operationId: create_ingredients
      tags:
        - ingredients
      requestBody:
        description: Creates a ingredient by payload. If the id/name exists, it errors
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ingredient"
      responses:
        "201":
          description: Newly created ingredient
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ingredient"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /recipes:
    get:
      summary: List all recipes
      operationId: list_recipes
      tags:
        - recipes
      parameters:
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: A paged array of recipes
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedRecipes"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a recipe
      operationId: create_recipes
      tags:
        - recipes
      requestBody:
        description: Creates a recipe by payload. If the id/name exists, it errors
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecipeWrapper"
      responses:
        "201":
          description: Newly created recipe
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecipeWrapper"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /recipes/{recipe_id}:
    get:
      summary: Info for a specific recipe
      operationId: get_recipe_by_id
      tags:
        - recipes
      parameters:
        - name: recipe_id
          in: path
          required: true
          description: The id of the recipe to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecipeWrapper"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /ingredients/{ingredient_id}/convert_to_recipe:
    post:
      summary: Converts an ingredient to a recipe, updating all recipes depending on it.
      operationId: convert_ingredient_to_recipe
      tags:
        - recipes
        - ingredients
      parameters:
        - name: ingredient_id
          in: path
          required: true
          description: The id of the ingredient
          schema:
            type: string
      responses:
        "201":
          description: Newly converted ingredient
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecipeDetail"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"                
security:
  - bearerAuth: [] # use the same name as above
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes

  schemas:
    SectionIngredient:
      description: Ingredients in a single section
      type: object
      required:
        - id
        - grams
        - kind
        - unit
        - adjective
      properties:
        id:
          description: id
          type: string
        kind:
          description: what kind of ingredient
          type: string
          enum: [recipe, ingredient]
        recipe:
          type: object
          $ref: "#/components/schemas/RecipeDetail"
        ingredient:
          type: object
          $ref: "#/components/schemas/Ingredient"
        grams:
          description: weight in grams
          type: number
          format: double # float64
        amount:
          description: amount
          type: number
          format: double # float64
        unit:
          description: unit
          type: string
        adjective:
          description: adjective
          type: string
        optional:
          description: optional
          type: boolean
    SectionInstruction:
      description: Instructions in a single section
      type: object
      required:
        - id
        - instruction
      properties:
        id:
          description: id
          type: string
        instruction:
          description: instruction
          type: string
    RecipeSection:
      description: A step in the recipe
      type: object
      required:
        - id
        - minutes
        - instructions
        - ingredients
      properties:
        id:
          description: id
          type: string
        minutes:
          description: How many minutes the step takes, approximately (todo - make this a range)
          type: integer
          format: int64
        instructions:
          description: x
          type: array
          items:
            $ref: "#/components/schemas/SectionInstruction"
        ingredients:
          description: x
          type: array
          items:
            $ref: "#/components/schemas/SectionIngredient"
    RecipeWrapper:
      description: A recipe with subcomponents
      type: object
      required:
        - detail
        - id
      properties:
        id:
          description: id
          type: string
        detail:
          description: The recipe
          $ref: "#/components/schemas/RecipeDetail"
    RecipeDetail:
      description: A revision of a recipe
      type: object
      required:
        - id
        - name
        - quantity
        - unit
        - sections
      properties:
        id:
          description: id
          type: string
        sections:
          description: sections of the recipe
          type: array
          items:
            $ref: "#/components/schemas/RecipeSection"          
        name:
          description: recipe name
          type: string
        total_minutes:
          description: todo
          type: integer
          format: int64
        source:
          description: book or website? deprecated?
          type: string
        servings:
          description: num servings
          type: integer
          format: int64
        quantity:
          description: serving quantity
          type: integer
          format: int64
        unit:
          description: serving unit
          type: string
        version:
          description: version of the recipe
          type: integer
          format: int64
        is_latest_version:
          description: whether or not it is the most recent version
          type: boolean
    Ingredient:
      description: "An Ingredient"
      type: object
      required:
        - id
        - name
      properties:
        id:
          description: id
          type: string
        name:
          description: Ingredient name
          type: string
    IngredientDetail:
      description: "An Ingredient"
      type: object
      required:
        - ingredient
      properties:
        ingredient:
          description: the ingredient
          type: object
          $ref: "#/components/schemas/Ingredient"
        recipes:
          description: Recipes referencing this ingredient
          type: array
          items:
            $ref: "#/components/schemas/RecipeDetail"
        children:
          description: Ingredients that are equivalent
          type: array
          items:
            $ref: "#/components/schemas/Ingredient"
    GooglePhotosAlbum:
      description: an album containing `GooglePhoto`
      type: object
      required:
        - id
        - title
        - product_url
        - usecase
      properties:
        id:
          description: id
          type: string        
        title:
          description: title
          type: string 
        product_url:
          description: product_url
          type: string
        usecase:
          description: usecase
          type: string          
    GooglePhoto:
      description: A google photo
      type: object
      required:
        - id
        - base_url
        - created
        - width
        - height
      properties:
        id:
          description: id
          type: string
        base_url:
          description: public image
          type: string
        blur_hash:
          description: blur hash
          type: string  
        created:
          description: when it was taken
          type: string
          format: date-time
        width:
          description: width px
          type: integer
          format: int64
        height:
          description: height px
          type: integer
          format: int64                  
    Meal:
      description: A google photo
      type: object
      required:
        - id
        - name
        - ate_at
        - photos
      properties:
        id:
          description: id
          type: string
        name:
          description: public image
          type: string
        ate_at:
          description: when it was taken
          type: string
          format: date-time
        photos:
          type: array
          items:
            $ref: "#/components/schemas/GooglePhoto"
    SearchResult:
      description: A search result wrapper, which contains ingredients and recipes
      type: object
      properties:
        ingredients:
          description: The ingredients
          type: array
          items:          
            $ref: "#/components/schemas/Ingredient" 
        recipes:
          description: The recipes
          type: array
          items:          
            $ref: "#/components/schemas/RecipeWrapper"            
    Error:
      type: object
      required: ["message"]
      properties:
        message:
          type: string
      example:
        message: "Something went wrong"
    AuthResp:
      type: object
      required:
        - user
        - jwt
      properties:
        user:
          type: object
        jwt:
          type: string
    List:
      type: object
      required:
        - page_number
        - limit
        - total_count
        - offset
        - page_count
      properties:
        page_number:
          description: What number page this is
          type: integer
        limit:
          description: How many items were requested for this page
          type: integer
        offset:
          description: todo
          type: integer
        total_count:
          description: Total number of items across all pages
          type: integer
        page_count:
          description: Total number of pages available
          type: integer

    PaginatedRecipes:
      type: object
      properties:
        recipes:
          type: array
          items:
            $ref: "#/components/schemas/RecipeDetail"
        meta:
          $ref: "#/components/schemas/List"
    PaginatedIngredients:
      type: object
      properties:
        ingredients:
          type: array
          items:
            $ref: "#/components/schemas/IngredientDetail"
        meta:
          $ref: "#/components/schemas/List"
    PaginatedPhotos:
      type: object
      properties:
        photos:
          type: array
          items:
            $ref: "#/components/schemas/GooglePhoto"
        meta:
          $ref: "#/components/schemas/List"
    PaginatedMeals:
      type: object
      properties:
        meals:
          type: array
          items:
            $ref: "#/components/schemas/Meal"
        meta:
          $ref: "#/components/schemas/List"
  parameters:
    offsetParam:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before starting to collect the result set.
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: The numbers of items to return.
    nameParam:
      in: query
      name: name
      required: true
      schema:
        type: string
      description: The search query (name).